-- Endereço completo (ex.: clientes base PR / PRL)

ALTER TABLE clients ADD COLUMN IF NOT EXISTS street VARCHAR(500);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS number VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS complement VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS zipcode VARCHAR(20);
